"use client";
/* eslint-disable react-hooks/exhaustive-deps */

import { RefreshCw, UserRound } from "lucide-react";
import { useEffect, useState } from "react";

import { AdminGuard } from "@/components/admin/AdminGuard";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/hooks/use-auth";
import type { UserProfile } from "@/types/auth";

export default function CustomersPage() { const { user } = useAuth(); const [customers, setCustomers] = useState<UserProfile[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); async function load() { if (!user) return; setLoading(true); setError(""); try { const response = await fetch("/api/admin/clientes", { headers: { Authorization: `Bearer ${await user.getIdToken()}` } }); const body = await response.json().catch(() => ({})) as { customers?: UserProfile[]; error?: string }; if (!response.ok) throw new Error(body.error ?? "No se pudieron cargar los clientes."); setCustomers(body.customers ?? []); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "No se pudieron cargar los clientes."); } finally { setLoading(false); } } useEffect(() => { void load(); }, [user]); return <AdminGuard permission="clientes.read"><div className="space-y-6"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-cyan-700">Relaciones</p><h1 className="mt-2 text-3xl font-bold text-slate-950">Clientes</h1><p className="mt-1 text-sm text-slate-500">Perfiles operativos de clientes, en modo solo lectura.</p></div><Button variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw className={loading ? "animate-spin" : ""} /> Actualizar</Button></div>{error && <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</p>}{loading ? <div className="h-40 animate-pulse rounded-xl bg-white" /> : customers.length === 0 ? <Card className="border-dashed bg-white"><CardContent className="p-10 text-center text-sm text-slate-500">No hay clientes registrados.</CardContent></Card> : <div className="grid gap-3 md:grid-cols-2">{customers.map((customer) => <Card key={customer.uid} className="border-slate-200 bg-white shadow-sm"><CardContent className="flex items-start gap-4 p-5"><span className="rounded-full bg-cyan-100 p-3 text-cyan-700"><UserRound className="h-5 w-5" /></span><div className="min-w-0"><h2 className="font-semibold text-slate-900">{customer.displayName ?? "Sin nombre"}</h2><p className="truncate text-sm text-slate-500">{customer.email}</p><p className="mt-2 text-xs text-slate-500">{customer.telefono ?? "Sin teléfono"} · {customer.addresses.length} direcciones</p></div></CardContent></Card>)}</div>}</div></AdminGuard>; }
